# Generated by Django 4.1.7 on 2023-05-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_books',
            field=models.ManyToManyField(blank=True, related_name='book_holders', to='eLibrary.book'),
        ),
    ]
